
// window defs
#define SCR_DECREASE_MULT 0.7
#define SCR_WIDTH 1920 * SCR_DECREASE_MULT
#define SCR_HEIGHT 1080 * SCR_DECREASE_MULT
#define WINDOW_TITLE "Layer Trains"

// palette
#define RENDER_BACKGROUND_COLOUR 132.f/255.f, 178.f/255.f, 179.f/255.f, 1.0f

// camera
#define CAMERA_FOV 55.f
#define CAMERA_NEAR_CLIP_PLANE 0.1f
#define CAMERA_FAR_CLIP_PLANE 100.f

#define CAMERA_ZOOM_SPEED .1f
#define CAMERA_MAX_ZOOM 4.f
#define CAMERA_MIN_ZOOM .01f
#define CAMERA_ROTATION_SPEED 5.f
#define CAMERA_MOVEMENT_SPEED .1f
#define CAMERA_SHIFT_SPEED_MULTIPLIER 2.5f

// CONTOUR MAP

// contour lines
#define ISO_LINE_THICKNESS .04f
#define ISO_LINE_SPACING 100.f // spacing of minor contouor lines in [m]
// #define CONTOUR_LINE_MAJOR_THICKNESS_MULTIPLER 3.f 
// #define CONTOUR_LINE_MAJOR_FREQUENCY 10 // every x minors there is a major
#define CONTOUR_LINE_COLOUR vec4(0.f,0.f,0.f,0.7f)
#define CONTOUR_LINE_HEGHT_OFFSET V3_Z * 0.0025f
#define CONTOUR_LINE_SCALING 1.01f

// contour map elevation data
#define ELEVATION_GRADIENT_MAX_HEIGHT 2500.f
#define ELEVATION_GRADIENT_STRENGTH .82f
#define STEEPNESS_SCALE 100.f
#define STEEPNESS_SMOOTHING_STEP_SIZE 5

#define OVERWRITE_CACHED_TEXTURES true

#define WATER_LEVEL_HEIGHT_DEFAULT 65.f

#define CURSOR_INNER_RADIUS 0.01f
#define CURSOR_OUTER_RADIUS 0.02f
#define CONTOUR_LINE_TOLERANCE 0.01f

#define NEW_LINE_SEGMENT_V2 vec2(-10000.f, -10000.f)
#define NEW_LINE_SEGMENT_V3 vec3(-10000.f, -10000.f, -10000.f)

#define CONTOUR_LINE_MAX_DISTANCE_BTW_POINTS 0.025f

#define CALDEA_FONT "C:/Media/Creations/Documents/Fonts/Caladea/Caladea-Regular.ttf"
#define DOXANA_FONT "C:/Media/Creations/Documents/Fonts/Doxana - Font/DoxanaDigital.ttf"
#define DEFAULT_FONT CALDEA_FONT
//#define DEFAULT_FONT "C:/Windows/Fonts/DoxanaDigital-Regular.ttf"

#define INTERACTABLE_OBJECT_ALPHA 0.5f
#define INTERACTABLE_DEFUALT_COLOUR Colour::WHITE
#define INTERACTABLE_RENDER_RADUIS_MUTLIPLIER 0.75f
#define INTERACTABLE_HIGHLIGHTED_COLOUR Colour::GREY
#define INTERACTABLE_HIGHLIGHTED_OBJECT_ALPHA INTERACTABLE_OBJECT_ALPHA*.7f
#define INTERACTABLE_INTERACT_DISTANCE 0.02f

#define PATH_DRAW_SLOPE_CHANGE_SPEED .1f
#define PATH_COLOUR Colour::PURPLE
#define PATH_THICKNESS 8.f